server:
  port: 9200
spring:
  profiles:
#    active: local
#    active: dev
    active: prd
  application:
    name: IITP
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: test123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        globally_quoted_identifiers: true
        jdbc:
          time_zone: Asia/Seoul
  devtools:
    restart:
      log-condition-evaluation-delta: false
  web:
    resources:
      static-locations: classpath:/static/
graphql:
  servlet:
    cors-enabled: false
logging:
  level:
    kr.co.kesti: info
---
server:
  port: 9200
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://211.55.33.242:5432/pm10
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
---
server:
  port: 9200
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://211.55.33.242:5432/pm10
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
---
server:
  port: 9200
spring:
  config:
    activate:
      on-profile: prd
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/pm10
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
