server:
  port: 9200
spring:
  config:
    import: classpath:/datasource.yml
  application:
    name: IITP
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        show_sql: false
        format_sql: false
        globally_quoted_identifiers: true
        jdbc:
          time_zone: Asia/Seoul
  devtools:
    restart:
      log-condition-evaluation-delta: false
  web:
    resources:
      static-locations: classpath:/static/
graphql:
  servlet:
    cors-enabled: false
logging:
  level:
    kr.co.kesti: info
