server:
  port: 9200
spring:
  profiles:
    active: local
#    active: dev
#    active: prd
  application:
    name: IITP
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://211.55.33.242:5432/pm10
    username: postgres
    password: test123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        globally_quoted_identifiers: true
        jdbc:
          time_zone: Asia/Seoul
  devtools:
    restart:
      log-condition-evaluation-delta: false
  web:
    resources:
      static-locations: classpath:/static/
graphql:
  servlet:
    cors-enabled: false
    exception-handlers-enabled: true
    context-setting: per_query_with_instrumentation
logging:
  level:
    kr.co.kesti: info
---
server:
  port: 9200
spring:
  config:
    activate:
      on-profile: local
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
---
server:
  port: 9200
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
---
server:
  port: 9200
spring:
  config:
    activate:
      on-profile: prd
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
