name: IITP

on:
  push:
    branches: [dev]
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IITP_HOST }}
          port: ${{ secrets.REMOTE_IITP_SSH_PORT }}
          username: ${{ secrets.REMOTE_IITP_SSH_USERNAME }}
          password: ${{ secrets.REMOTE_IITP_SSH_PASSWORD }}
          script: |
            DEPLOY_PORT=9100
            cd /home/iitp
            if [ -d iitp ]; then rm -rf iitp; fi
            git clone https://github.com/kesti-ITBIZ/iitp.git
            cd iitp
            git branch dev
            cd frontend
            npm i
            cp ./font-awesome-pro-icons/* ./node_modules/@fortawesome/free-solid-svg-icons
            npm run build
            cd ..
            chmod +x ./gradlew
            ./gradlew bootWar
            if [ `docker ps | grep -c 'tomcat/iitp:beta'` != 0 ]; then
              docker stop iitp-dev
              docker rm iitp-dev
            fi
            if [ `docker images | grep -c 'tomcat/iitp:beta'` != 0 ]; then
              docker rmi tomcat/iitp:beta
            fi
            docker build -t tomcat/iitp:beta .
            docker rmi java:8
            docker run -d --name iitp-dev -p $DEPLOY_PORT:9200 tomcat/iitp:beta
            cd ..
            if [ -d iitp ]; then rm -rf iitp; fi
