name: IITP

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IITP_HOST }}
          port: ${{ secrets.REMOTE_IITP_SSH_PORT }}
          username: ${{ secrets.REMOTE_IITP_SSH_USERNAME }}
          password: ${{ secrets.REMOTE_IITP_SSH_PASSWORD }}
          script: |
            cd /home/iitp
            git clone https://github.com/kesti-ITBIZ/iitp.git
            cd ./iitp
            git checkout main
            cd ./frontend
            npm i
            npm run build
            cd ..
            chmod +x ./gradlew
            ./gradlew bootWar
            docker build -t tomcat/iitp:latest .
            docker rmi java:8
            docker run -d --name iitp -p 9200:9200 tomcat/iitp:latest
            cd ..
            rm -rf iitp
