# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: IITP

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    name: Build front-end codes
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Change directory to frontend
        run: cd frontend

      - name: Build front-end codes
        uses: actions/setup-node@v2
          with:
            node-version: '14'
        run: npm run build

      - name: Change to parent directory
        run: cd ..
